// Generated by Scripts/convert_harmonicc_styles.py from the Harmonicc style tables.
// Edit the script and generate the file again. Do not edit this file by hand.

import HarmonyEngine

public extension StyleProfile {
    /// General.
    static let general = StyleProfile(
        id: "general",
        name: "General",
        transitions: [
            DegreeTransition(from: 1, to: 1, weight: 0.3),
            DegreeTransition(from: 1, to: 4, weight: 0.8),
            DegreeTransition(from: 1, to: 5, weight: 0.65),
            DegreeTransition(from: 1, to: 2, weight: 0.5),
            DegreeTransition(from: 1, to: 6, weight: 0.4),
            DegreeTransition(from: 1, to: 3, weight: 0.35),
            DegreeTransition(from: 1, to: 7, weight: 0.3),
            DegreeTransition(from: 2, to: 5, weight: 1.0),
            DegreeTransition(from: 2, to: 4, weight: 0.8),
            DegreeTransition(from: 2, to: 7, weight: 0.65),
            DegreeTransition(from: 3, to: 6, weight: 1.0),
            DegreeTransition(from: 3, to: 4, weight: 0.8),
            DegreeTransition(from: 3, to: 5, weight: 0.65),
            DegreeTransition(from: 3, to: 1, weight: 0.5),
            DegreeTransition(from: 3, to: 7, weight: 0.4),
            DegreeTransition(from: 4, to: 5, weight: 1.0),
            DegreeTransition(from: 4, to: 2, weight: 0.8),
            DegreeTransition(from: 4, to: 1, weight: 0.65),
            DegreeTransition(from: 4, to: 7, weight: 0.5),
            DegreeTransition(from: 5, to: 1, weight: 1.0),
            DegreeTransition(from: 5, to: 6, weight: 0.8),
            DegreeTransition(from: 5, to: 3, weight: 0.65),
            DegreeTransition(from: 5, to: 4, weight: 0.5),
            DegreeTransition(from: 5, to: 7, weight: 0.4),
            DegreeTransition(from: 6, to: 2, weight: 1.0),
            DegreeTransition(from: 6, to: 4, weight: 0.8),
            DegreeTransition(from: 6, to: 5, weight: 0.65),
            DegreeTransition(from: 6, to: 1, weight: 0.5),
            DegreeTransition(from: 6, to: 7, weight: 0.4),
            DegreeTransition(from: 7, to: 1, weight: 1.0),
            DegreeTransition(from: 7, to: 5, weight: 0.8),
            DegreeTransition(from: 7, to: 6, weight: 0.65),
        ],
        flavors: [.triad: 1.0, .dominantSeventh: 1.0, .seventh: 1.0, .ninth: 0.4, .eleventh: 0.3],
        alterations: [.flatNinth, .sharpEleventh],
        devices: [
            DeviceWeight(.appliedDominant(target: 5), weight: 0.6),
            DeviceWeight(.cadentialSixFour, weight: 0.5),
        ],
        cadenceStrength: 1.0,
        voicing: VoicingOptions()
    )

    /// Baroque.
    static let baroque = StyleProfile(
        id: "baroque",
        name: "Baroque",
        transitions: [
            DegreeTransition(from: 1, to: 4, weight: 1.0),
            DegreeTransition(from: 1, to: 5, weight: 0.8),
            DegreeTransition(from: 1, to: 2, weight: 0.65),
            DegreeTransition(from: 2, to: 5, weight: 1.0),
            DegreeTransition(from: 3, to: 4, weight: 1.0),
            DegreeTransition(from: 3, to: 6, weight: 0.8),
            DegreeTransition(from: 4, to: 5, weight: 1.0),
            DegreeTransition(from: 4, to: 2, weight: 0.8),
            DegreeTransition(from: 5, to: 1, weight: 1.0),
            DegreeTransition(from: 6, to: 2, weight: 1.0),
            DegreeTransition(from: 6, to: 4, weight: 0.8),
            DegreeTransition(from: 7, to: 1, weight: 1.0),
        ],
        flavors: [.triad: 1.0, .dominantSeventh: 1.0, .seventh: 0.2],
        alterations: [],
        devices: [
            DeviceWeight(.cadentialSixFour, weight: 0.5),
            DeviceWeight(.appliedDominant(target: 5), weight: 0.6),
        ],
        cadenceStrength: 1.0,
        voicing: VoicingOptions()
    )

    /// Classical.
    static let classical = StyleProfile(
        id: "classical",
        name: "Classical",
        transitions: [
            DegreeTransition(from: 1, to: 5, weight: 1.0),
            DegreeTransition(from: 1, to: 4, weight: 0.8),
            DegreeTransition(from: 1, to: 2, weight: 0.65),
            DegreeTransition(from: 2, to: 5, weight: 1.0),
            DegreeTransition(from: 2, to: 4, weight: 0.8),
            DegreeTransition(from: 3, to: 4, weight: 1.0),
            DegreeTransition(from: 3, to: 6, weight: 0.8),
            DegreeTransition(from: 4, to: 5, weight: 1.0),
            DegreeTransition(from: 4, to: 1, weight: 0.8),
            DegreeTransition(from: 4, to: 2, weight: 0.65),
            DegreeTransition(from: 5, to: 1, weight: 1.0),
            DegreeTransition(from: 5, to: 6, weight: 0.8),
            DegreeTransition(from: 6, to: 2, weight: 1.0),
            DegreeTransition(from: 6, to: 4, weight: 0.8),
            DegreeTransition(from: 7, to: 1, weight: 1.0),
        ],
        flavors: [.triad: 1.0, .dominantSeventh: 1.0, .seventh: 0.2],
        alterations: [],
        devices: [
            DeviceWeight(.cadentialSixFour, weight: 0.5),
            DeviceWeight(.neapolitan, weight: 0.5),
        ],
        cadenceStrength: 1.0,
        voicing: VoicingOptions()
    )

    /// Romantic.
    static let romantic = StyleProfile(
        id: "romantic",
        name: "Romantic",
        transitions: [
            DegreeTransition(from: 1, to: 3, weight: 1.0),
            DegreeTransition(from: 1, to: 6, weight: 0.8),
            DegreeTransition(from: 1, to: 4, weight: 0.65),
            DegreeTransition(from: 2, to: 5, weight: 1.0),
            DegreeTransition(from: 3, to: 6, weight: 1.0),
            DegreeTransition(from: 3, to: 4, weight: 0.8),
            DegreeTransition(from: 4, to: 5, weight: 1.0),
            DegreeTransition(from: 4, to: 2, weight: 0.8),
            DegreeTransition(from: 5, to: 1, weight: 1.0),
            DegreeTransition(from: 5, to: 6, weight: 0.8),
            DegreeTransition(from: 6, to: 2, weight: 1.0),
            DegreeTransition(from: 6, to: 3, weight: 0.8),
            DegreeTransition(from: 7, to: 1, weight: 1.0),
            DegreeTransition(from: 7, to: 6, weight: 0.8),
        ],
        flavors: [.triad: 1.0, .dominantSeventh: 1.0, .seventh: 1.0, .ninth: 0.4],
        alterations: [.flatNinth, .sharpEleventh, .flatThirteenth],
        devices: [
            DeviceWeight(.augmentedSixth(.german), weight: 0.5),
            DeviceWeight(.augmentedSixth(.french), weight: 0.5),
            DeviceWeight(.augmentedSixth(.italian), weight: 0.5),
            DeviceWeight(.neapolitan, weight: 0.5),
            DeviceWeight(.appliedDominant(target: 3), weight: 0.6),
            DeviceWeight(.appliedDominant(target: 6), weight: 0.6),
            DeviceWeight(.appliedDominant(target: 2), weight: 0.4),
            DeviceWeight(.appliedDominant(target: 5), weight: 0.4),
            DeviceWeight(.appliedLeadingTone(target: 2), weight: 0.4),
            DeviceWeight(.appliedLeadingTone(target: 5), weight: 0.4),
            DeviceWeight(.borrowed(degree: 4, from: .minor), weight: 0.5),
            DeviceWeight(.borrowed(degree: 6, from: .minor), weight: 0.5),
            DeviceWeight(.borrowed(degree: 3, from: .minor), weight: 0.5),
        ],
        cadenceStrength: 1.0,
        voicing: VoicingOptions()
    )

    /// Swing.
    static let swing = StyleProfile(
        id: "swing",
        name: "Swing",
        transitions: [
            DegreeTransition(from: 1, to: 2, weight: 1.0),
            DegreeTransition(from: 1, to: 4, weight: 0.8),
            DegreeTransition(from: 1, to: 6, weight: 0.65),
            DegreeTransition(from: 2, to: 5, weight: 1.0),
            DegreeTransition(from: 3, to: 6, weight: 1.0),
            DegreeTransition(from: 3, to: 2, weight: 0.8),
            DegreeTransition(from: 4, to: 5, weight: 1.0),
            DegreeTransition(from: 4, to: 2, weight: 0.8),
            DegreeTransition(from: 4, to: 1, weight: 0.65),
            DegreeTransition(from: 5, to: 1, weight: 1.0),
            DegreeTransition(from: 5, to: 6, weight: 0.8),
            DegreeTransition(from: 6, to: 2, weight: 1.0),
            DegreeTransition(from: 6, to: 5, weight: 0.8),
            DegreeTransition(from: 7, to: 1, weight: 1.0),
            DegreeTransition(from: 7, to: 6, weight: 0.8),
        ],
        flavors: [.triad: 0.3, .dominantSeventh: 1.0, .seventh: 1.0, .ninth: 0.4, .thirteenth: 0.3, .sixNine: 0.5],
        alterations: [.flatNinth, .sharpEleventh],
        devices: [
            DeviceWeight(.appliedDominant(target: 2), weight: 0.6),
            DeviceWeight(.appliedDominant(target: 5), weight: 0.6),
            DeviceWeight(.relatedSupertonic(target: 2), weight: 0.4),
            DeviceWeight(.relatedSupertonic(target: 5), weight: 0.4),
        ],
        cadenceStrength: 1.0,
        voicing: VoicingOptions(style: .drop2, bassMode: .root)
    )

    /// Bebop.
    static let bebop = StyleProfile(
        id: "bebop",
        name: "Bebop",
        transitions: [
            DegreeTransition(from: 1, to: 2, weight: 1.0),
            DegreeTransition(from: 1, to: 4, weight: 0.8),
            DegreeTransition(from: 1, to: 5, weight: 0.65),
            DegreeTransition(from: 2, to: 5, weight: 1.0),
            DegreeTransition(from: 2, to: 4, weight: 0.8),
            DegreeTransition(from: 3, to: 6, weight: 1.0),
            DegreeTransition(from: 3, to: 2, weight: 0.8),
            DegreeTransition(from: 4, to: 5, weight: 1.0),
            DegreeTransition(from: 4, to: 2, weight: 0.8),
            DegreeTransition(from: 4, to: 1, weight: 0.65),
            DegreeTransition(from: 5, to: 1, weight: 1.0),
            DegreeTransition(from: 5, to: 6, weight: 0.8),
            DegreeTransition(from: 5, to: 2, weight: 0.65),
            DegreeTransition(from: 6, to: 2, weight: 1.0),
            DegreeTransition(from: 6, to: 5, weight: 0.8),
            DegreeTransition(from: 7, to: 1, weight: 1.0),
            DegreeTransition(from: 7, to: 5, weight: 0.8),
        ],
        flavors: [.triad: 0.3, .dominantSeventh: 1.0, .seventh: 1.0, .ninth: 0.4, .eleventh: 0.3, .thirteenth: 0.3],
        alterations: [.flatNinth, .sharpNinth, .sharpEleventh, .flatThirteenth],
        devices: [
            DeviceWeight(.tritoneSubstitute(target: 1), weight: 0.6),
            DeviceWeight(.appliedDominant(target: 2), weight: 0.6),
            DeviceWeight(.appliedDominant(target: 3), weight: 0.6),
            DeviceWeight(.appliedDominant(target: 5), weight: 0.6),
            DeviceWeight(.appliedDominant(target: 6), weight: 0.6),
            DeviceWeight(.appliedLeadingTone(target: 2), weight: 0.4),
            DeviceWeight(.appliedLeadingTone(target: 5), weight: 0.4),
            DeviceWeight(.tritoneSubstitute(target: 2), weight: 0.5),
            DeviceWeight(.tritoneSubstitute(target: 5), weight: 0.5),
            DeviceWeight(.commonToneDiminished, weight: 0.4),
            DeviceWeight(.relatedSupertonic(target: 2), weight: 0.4),
            DeviceWeight(.relatedSupertonic(target: 3), weight: 0.4),
            DeviceWeight(.relatedSupertonic(target: 5), weight: 0.4),
            DeviceWeight(.relatedSupertonic(target: 6), weight: 0.4),
        ],
        cadenceStrength: 1.0,
        voicing: VoicingOptions(style: .drop2, bassMode: .root)
    )

    /// Modal.
    static let modal = StyleProfile(
        id: "modal",
        name: "Modal",
        transitions: [
            DegreeTransition(from: 1, to: 3, weight: 1.0),
            DegreeTransition(from: 1, to: 4, weight: 0.8),
            DegreeTransition(from: 1, to: 6, weight: 0.65),
            DegreeTransition(from: 2, to: 3, weight: 1.0),
            DegreeTransition(from: 2, to: 4, weight: 0.8),
            DegreeTransition(from: 3, to: 4, weight: 1.0),
            DegreeTransition(from: 3, to: 6, weight: 0.8),
            DegreeTransition(from: 4, to: 3, weight: 1.0),
            DegreeTransition(from: 4, to: 1, weight: 0.8),
            DegreeTransition(from: 4, to: 6, weight: 0.65),
            DegreeTransition(from: 5, to: 6, weight: 1.0),
            DegreeTransition(from: 5, to: 3, weight: 0.8),
            DegreeTransition(from: 6, to: 3, weight: 1.0),
            DegreeTransition(from: 6, to: 1, weight: 0.8),
            DegreeTransition(from: 7, to: 3, weight: 1.0),
            DegreeTransition(from: 7, to: 6, weight: 0.8),
        ],
        flavors: [.triad: 1.0, .dominantSeventh: 0.35, .seventh: 1.0, .ninth: 0.4, .eleventh: 0.3, .sus2: 0.5, .sus4: 0.5],
        alterations: [.sharpEleventh],
        devices: [
            DeviceWeight(.appliedDominant(target: 3), weight: 0.6),
            DeviceWeight(.appliedDominant(target: 6), weight: 0.6),
            DeviceWeight(.appliedLeadingTone(target: 2), weight: 0.4),
            DeviceWeight(.appliedLeadingTone(target: 5), weight: 0.4),
            DeviceWeight(.borrowed(degree: 1, from: .minor), weight: 0.5),
            DeviceWeight(.borrowed(degree: 2, from: .phrygian), weight: 0.4),
            DeviceWeight(.borrowed(degree: 3, from: .minor), weight: 0.5),
            DeviceWeight(.borrowed(degree: 6, from: .minor), weight: 0.5),
        ],
        cadenceStrength: 0.3,
        voicing: VoicingOptions()
    )

    /// Fusion.
    static let fusion = StyleProfile(
        id: "fusion",
        name: "Fusion",
        transitions: [
            DegreeTransition(from: 1, to: 4, weight: 1.0),
            DegreeTransition(from: 1, to: 3, weight: 0.8),
            DegreeTransition(from: 1, to: 6, weight: 0.65),
            DegreeTransition(from: 2, to: 5, weight: 1.0),
            DegreeTransition(from: 2, to: 4, weight: 0.8),
            DegreeTransition(from: 3, to: 4, weight: 1.0),
            DegreeTransition(from: 3, to: 6, weight: 0.8),
            DegreeTransition(from: 4, to: 5, weight: 1.0),
            DegreeTransition(from: 4, to: 3, weight: 0.8),
            DegreeTransition(from: 4, to: 1, weight: 0.65),
            DegreeTransition(from: 5, to: 1, weight: 1.0),
            DegreeTransition(from: 5, to: 6, weight: 0.8),
            DegreeTransition(from: 5, to: 3, weight: 0.65),
            DegreeTransition(from: 6, to: 3, weight: 1.0),
            DegreeTransition(from: 6, to: 4, weight: 0.8),
            DegreeTransition(from: 7, to: 1, weight: 1.0),
            DegreeTransition(from: 7, to: 3, weight: 0.8),
        ],
        flavors: [.triad: 0.3, .dominantSeventh: 1.0, .seventh: 1.0, .ninth: 0.4, .eleventh: 0.3, .thirteenth: 0.3, .sus2: 0.5, .sus4: 0.5, .add9: 0.5, .sixNine: 0.5],
        alterations: [.flatNinth, .sharpNinth, .sharpEleventh, .flatThirteenth],
        devices: [
            DeviceWeight(.tritoneSubstitute(target: 1), weight: 0.6),
            DeviceWeight(.appliedDominant(target: 2), weight: 0.6),
            DeviceWeight(.appliedDominant(target: 3), weight: 0.6),
            DeviceWeight(.appliedDominant(target: 5), weight: 0.6),
            DeviceWeight(.tritoneSubstitute(target: 2), weight: 0.5),
            DeviceWeight(.tritoneSubstitute(target: 5), weight: 0.5),
            DeviceWeight(.borrowed(degree: 4, from: .minor), weight: 0.5),
            DeviceWeight(.borrowed(degree: 3, from: .minor), weight: 0.5),
            DeviceWeight(.relatedSupertonic(target: 2), weight: 0.4),
            DeviceWeight(.relatedSupertonic(target: 3), weight: 0.4),
            DeviceWeight(.relatedSupertonic(target: 5), weight: 0.4),
        ],
        cadenceStrength: 0.6,
        voicing: VoicingOptions(style: .drop2, bassMode: .root)
    )

    /// Jazz.
    static let jazz = StyleProfile(
        id: "jazz",
        name: "Jazz",
        transitions: [
            DegreeTransition(from: 1, to: 4, weight: 1.0),
            DegreeTransition(from: 1, to: 2, weight: 0.8),
            DegreeTransition(from: 1, to: 6, weight: 0.65),
            DegreeTransition(from: 2, to: 5, weight: 1.0),
            DegreeTransition(from: 3, to: 6, weight: 1.0),
            DegreeTransition(from: 3, to: 2, weight: 0.8),
            DegreeTransition(from: 4, to: 5, weight: 1.0),
            DegreeTransition(from: 4, to: 2, weight: 0.8),
            DegreeTransition(from: 4, to: 1, weight: 0.65),
            DegreeTransition(from: 5, to: 1, weight: 1.0),
            DegreeTransition(from: 5, to: 6, weight: 0.8),
            DegreeTransition(from: 6, to: 2, weight: 1.0),
            DegreeTransition(from: 6, to: 5, weight: 0.8),
            DegreeTransition(from: 7, to: 1, weight: 1.0),
            DegreeTransition(from: 7, to: 5, weight: 0.8),
        ],
        flavors: [.triad: 0.3, .dominantSeventh: 1.0, .seventh: 1.0, .ninth: 0.4, .eleventh: 0.3, .thirteenth: 0.3],
        alterations: [.flatNinth, .sharpNinth, .sharpEleventh, .flatThirteenth],
        devices: [
            DeviceWeight(.tritoneSubstitute(target: 1), weight: 0.6),
            DeviceWeight(.appliedDominant(target: 2), weight: 0.6),
            DeviceWeight(.appliedDominant(target: 3), weight: 0.6),
            DeviceWeight(.appliedDominant(target: 5), weight: 0.6),
            DeviceWeight(.appliedDominant(target: 6), weight: 0.6),
            DeviceWeight(.appliedLeadingTone(target: 2), weight: 0.4),
            DeviceWeight(.appliedLeadingTone(target: 5), weight: 0.4),
            DeviceWeight(.tritoneSubstitute(target: 2), weight: 0.5),
            DeviceWeight(.tritoneSubstitute(target: 5), weight: 0.5),
            DeviceWeight(.commonToneDiminished, weight: 0.4),
            DeviceWeight(.borrowed(degree: 4, from: .minor), weight: 0.5),
            DeviceWeight(.borrowed(degree: 3, from: .minor), weight: 0.5),
            DeviceWeight(.borrowed(degree: 6, from: .minor), weight: 0.5),
            DeviceWeight(.relatedSupertonic(target: 2), weight: 0.4),
            DeviceWeight(.relatedSupertonic(target: 3), weight: 0.4),
            DeviceWeight(.relatedSupertonic(target: 5), weight: 0.4),
            DeviceWeight(.relatedSupertonic(target: 6), weight: 0.4),
        ],
        cadenceStrength: 1.0,
        voicing: VoicingOptions(style: .drop2, bassMode: .root)
    )

    /// Pop.
    static let pop = StyleProfile(
        id: "pop",
        name: "Pop",
        transitions: [
            DegreeTransition(from: 1, to: 4, weight: 1.0),
            DegreeTransition(from: 1, to: 5, weight: 0.8),
            DegreeTransition(from: 1, to: 6, weight: 0.65),
            DegreeTransition(from: 2, to: 5, weight: 1.0),
            DegreeTransition(from: 2, to: 4, weight: 0.8),
            DegreeTransition(from: 3, to: 4, weight: 1.0),
            DegreeTransition(from: 3, to: 6, weight: 0.8),
            DegreeTransition(from: 4, to: 1, weight: 1.0),
            DegreeTransition(from: 4, to: 5, weight: 0.8),
            DegreeTransition(from: 4, to: 6, weight: 0.65),
            DegreeTransition(from: 5, to: 1, weight: 1.0),
            DegreeTransition(from: 5, to: 6, weight: 0.8),
            DegreeTransition(from: 6, to: 4, weight: 1.0),
            DegreeTransition(from: 6, to: 5, weight: 0.8),
            DegreeTransition(from: 7, to: 1, weight: 1.0),
        ],
        flavors: [.triad: 1.0, .dominantSeventh: 0.35, .seventh: 0.2, .ninth: 0.4, .sus2: 0.5, .sus4: 0.5, .add9: 0.5],
        alterations: [],
        devices: [],
        cadenceStrength: 1.0,
        voicing: VoicingOptions()
    )

    /// Rock.
    static let rock = StyleProfile(
        id: "rock",
        name: "Rock",
        transitions: [
            DegreeTransition(from: 1, to: 4, weight: 1.0),
            DegreeTransition(from: 1, to: 5, weight: 0.8),
            DegreeTransition(from: 1, to: 6, weight: 0.65),
            DegreeTransition(from: 2, to: 5, weight: 1.0),
            DegreeTransition(from: 3, to: 4, weight: 1.0),
            DegreeTransition(from: 4, to: 1, weight: 1.0),
            DegreeTransition(from: 4, to: 5, weight: 0.8),
            DegreeTransition(from: 5, to: 1, weight: 1.0),
            DegreeTransition(from: 5, to: 4, weight: 0.8),
            DegreeTransition(from: 6, to: 4, weight: 1.0),
            DegreeTransition(from: 6, to: 2, weight: 0.8),
            DegreeTransition(from: 7, to: 1, weight: 1.0),
        ],
        flavors: [.triad: 1.0, .dominantSeventh: 0.35, .seventh: 0.2, .sus2: 0.5, .sus4: 0.5],
        alterations: [],
        devices: [
            DeviceWeight(.borrowed(degree: 7, from: .minor), weight: 0.5),
            DeviceWeight(.borrowed(degree: 3, from: .minor), weight: 0.5),
            DeviceWeight(.borrowed(degree: 6, from: .minor), weight: 0.5),
        ],
        cadenceStrength: 1.0,
        voicing: VoicingOptions()
    )

    /// Folk.
    static let folk = StyleProfile(
        id: "folk",
        name: "Folk",
        transitions: [
            DegreeTransition(from: 1, to: 4, weight: 1.0),
            DegreeTransition(from: 1, to: 5, weight: 0.8),
            DegreeTransition(from: 1, to: 6, weight: 0.65),
            DegreeTransition(from: 2, to: 5, weight: 1.0),
            DegreeTransition(from: 3, to: 4, weight: 1.0),
            DegreeTransition(from: 4, to: 1, weight: 1.0),
            DegreeTransition(from: 4, to: 5, weight: 0.8),
            DegreeTransition(from: 5, to: 1, weight: 1.0),
            DegreeTransition(from: 5, to: 6, weight: 0.8),
            DegreeTransition(from: 6, to: 4, weight: 1.0),
            DegreeTransition(from: 6, to: 5, weight: 0.8),
            DegreeTransition(from: 7, to: 1, weight: 1.0),
        ],
        flavors: [.triad: 1.0, .dominantSeventh: 0.35, .seventh: 0.2, .sus2: 0.5, .sus4: 0.5],
        alterations: [],
        devices: [],
        cadenceStrength: 1.0,
        voicing: VoicingOptions()
    )

    /// Blues.
    static let blues = StyleProfile(
        id: "blues",
        name: "Blues",
        transitions: [
            DegreeTransition(from: 1, to: 4, weight: 1.0),
            DegreeTransition(from: 1, to: 5, weight: 0.8),
            DegreeTransition(from: 2, to: 1, weight: 1.0),
            DegreeTransition(from: 2, to: 4, weight: 0.8),
            DegreeTransition(from: 2, to: 5, weight: 0.65),
            DegreeTransition(from: 3, to: 1, weight: 1.0),
            DegreeTransition(from: 3, to: 4, weight: 0.8),
            DegreeTransition(from: 3, to: 5, weight: 0.65),
            DegreeTransition(from: 4, to: 1, weight: 1.0),
            DegreeTransition(from: 4, to: 5, weight: 0.8),
            DegreeTransition(from: 5, to: 1, weight: 1.0),
            DegreeTransition(from: 5, to: 4, weight: 0.8),
            DegreeTransition(from: 6, to: 1, weight: 1.0),
            DegreeTransition(from: 6, to: 4, weight: 0.8),
            DegreeTransition(from: 6, to: 5, weight: 0.65),
            DegreeTransition(from: 7, to: 1, weight: 1.0),
            DegreeTransition(from: 7, to: 4, weight: 0.8),
            DegreeTransition(from: 7, to: 5, weight: 0.65),
        ],
        flavors: [.triad: 0.3, .dominantSeventh: 1.0, .seventh: 0.2, .bluesSeventh: 1.0],
        alterations: [.sharpEleventh, .flatThirteenth],
        devices: [],
        cadenceStrength: 1.0,
        voicing: VoicingOptions()
    )

    /// Funk.
    static let funk = StyleProfile(
        id: "funk",
        name: "Funk",
        transitions: [
            DegreeTransition(from: 1, to: 4, weight: 1.0),
            DegreeTransition(from: 1, to: 2, weight: 0.8),
            DegreeTransition(from: 2, to: 5, weight: 1.0),
            DegreeTransition(from: 3, to: 4, weight: 1.0),
            DegreeTransition(from: 3, to: 6, weight: 0.8),
            DegreeTransition(from: 4, to: 1, weight: 1.0),
            DegreeTransition(from: 4, to: 5, weight: 0.8),
            DegreeTransition(from: 5, to: 1, weight: 1.0),
            DegreeTransition(from: 5, to: 4, weight: 0.8),
            DegreeTransition(from: 5, to: 6, weight: 0.65),
            DegreeTransition(from: 6, to: 2, weight: 1.0),
            DegreeTransition(from: 6, to: 4, weight: 0.8),
            DegreeTransition(from: 7, to: 1, weight: 1.0),
        ],
        flavors: [.triad: 0.3, .dominantSeventh: 1.0, .seventh: 1.0, .ninth: 0.4, .eleventh: 0.3, .thirteenth: 0.3, .sus4: 0.5, .sevenSus4: 0.5, .add9: 0.5, .sixNine: 0.5],
        alterations: [.flatNinth, .sharpNinth, .sharpEleventh, .flatThirteenth],
        devices: [
            DeviceWeight(.appliedDominant(target: 2), weight: 0.4),
            DeviceWeight(.appliedDominant(target: 5), weight: 0.4),
            DeviceWeight(.borrowed(degree: 4, from: .minor), weight: 0.5),
            DeviceWeight(.borrowed(degree: 7, from: .minor), weight: 0.5),
        ],
        cadenceStrength: 0.6,
        voicing: VoicingOptions(style: .drop2, bassMode: .root)
    )

    /// R&B.
    static let rAndB = StyleProfile(
        id: "rAndB",
        name: "R&B",
        transitions: [
            DegreeTransition(from: 1, to: 4, weight: 1.0),
            DegreeTransition(from: 1, to: 6, weight: 0.8),
            DegreeTransition(from: 2, to: 5, weight: 1.0),
            DegreeTransition(from: 2, to: 4, weight: 0.8),
            DegreeTransition(from: 3, to: 4, weight: 1.0),
            DegreeTransition(from: 3, to: 6, weight: 0.8),
            DegreeTransition(from: 4, to: 1, weight: 1.0),
            DegreeTransition(from: 4, to: 5, weight: 0.8),
            DegreeTransition(from: 4, to: 6, weight: 0.65),
            DegreeTransition(from: 5, to: 1, weight: 1.0),
            DegreeTransition(from: 5, to: 6, weight: 0.8),
            DegreeTransition(from: 6, to: 2, weight: 1.0),
            DegreeTransition(from: 6, to: 4, weight: 0.8),
            DegreeTransition(from: 7, to: 1, weight: 1.0),
            DegreeTransition(from: 7, to: 6, weight: 0.8),
        ],
        flavors: [.triad: 0.3, .dominantSeventh: 1.0, .seventh: 1.0, .ninth: 0.4, .eleventh: 0.3, .thirteenth: 0.3, .add9: 0.5],
        alterations: [.sharpNinth, .flatThirteenth],
        devices: [
            DeviceWeight(.tritoneSubstitute(target: 1), weight: 0.6),
        ],
        cadenceStrength: 0.6,
        voicing: VoicingOptions(style: .drop2, bassMode: .root)
    )

    /// Contemporary.
    static let contemporary = StyleProfile(
        id: "contemporary",
        name: "Contemporary",
        transitions: [
            DegreeTransition(from: 1, to: 1, weight: 0.3),
            DegreeTransition(from: 1, to: 2, weight: 0.6),
            DegreeTransition(from: 1, to: 3, weight: 0.6),
            DegreeTransition(from: 1, to: 4, weight: 0.6),
            DegreeTransition(from: 1, to: 5, weight: 0.6),
            DegreeTransition(from: 1, to: 6, weight: 0.6),
            DegreeTransition(from: 1, to: 7, weight: 0.6),
            DegreeTransition(from: 2, to: 5, weight: 1.0),
            DegreeTransition(from: 2, to: 4, weight: 0.8),
            DegreeTransition(from: 3, to: 6, weight: 1.0),
            DegreeTransition(from: 3, to: 4, weight: 0.8),
            DegreeTransition(from: 4, to: 1, weight: 1.0),
            DegreeTransition(from: 4, to: 6, weight: 0.8),
            DegreeTransition(from: 4, to: 2, weight: 0.65),
            DegreeTransition(from: 5, to: 1, weight: 1.0),
            DegreeTransition(from: 5, to: 6, weight: 0.8),
            DegreeTransition(from: 5, to: 4, weight: 0.65),
            DegreeTransition(from: 6, to: 4, weight: 1.0),
            DegreeTransition(from: 6, to: 2, weight: 0.8),
            DegreeTransition(from: 7, to: 1, weight: 1.0),
            DegreeTransition(from: 7, to: 6, weight: 0.8),
        ],
        flavors: [.triad: 1.0, .dominantSeventh: 1.0, .seventh: 1.0, .ninth: 0.4, .eleventh: 0.3, .thirteenth: 0.3, .sus2: 0.5, .sus4: 0.5, .add9: 0.5],
        alterations: [.flatNinth, .sharpNinth, .sharpEleventh, .flatThirteenth],
        devices: [
            DeviceWeight(.appliedDominant(target: 2), weight: 0.6),
            DeviceWeight(.appliedDominant(target: 3), weight: 0.6),
            DeviceWeight(.appliedDominant(target: 4), weight: 0.6),
            DeviceWeight(.appliedDominant(target: 5), weight: 0.6),
            DeviceWeight(.appliedDominant(target: 6), weight: 0.6),
            DeviceWeight(.tritoneSubstitute(target: 2), weight: 0.5),
            DeviceWeight(.tritoneSubstitute(target: 5), weight: 0.5),
            DeviceWeight(.tritoneSubstitute(target: 1), weight: 0.6),
            DeviceWeight(.appliedLeadingTone(target: 2), weight: 0.4),
            DeviceWeight(.appliedLeadingTone(target: 5), weight: 0.4),
            DeviceWeight(.borrowed(degree: 4, from: .minor), weight: 0.5),
            DeviceWeight(.borrowed(degree: 6, from: .minor), weight: 0.5),
            DeviceWeight(.borrowed(degree: 3, from: .minor), weight: 0.5),
        ],
        cadenceStrength: 0.6,
        voicing: VoicingOptions()
    )

    /// Ambient.
    static let ambient = StyleProfile(
        id: "ambient",
        name: "Ambient",
        transitions: [
            DegreeTransition(from: 1, to: 3, weight: 1.0),
            DegreeTransition(from: 1, to: 6, weight: 0.8),
            DegreeTransition(from: 1, to: 4, weight: 0.65),
            DegreeTransition(from: 2, to: 4, weight: 1.0),
            DegreeTransition(from: 2, to: 3, weight: 0.8),
            DegreeTransition(from: 3, to: 6, weight: 1.0),
            DegreeTransition(from: 3, to: 4, weight: 0.8),
            DegreeTransition(from: 4, to: 3, weight: 1.0),
            DegreeTransition(from: 4, to: 1, weight: 0.8),
            DegreeTransition(from: 4, to: 6, weight: 0.65),
            DegreeTransition(from: 5, to: 6, weight: 1.0),
            DegreeTransition(from: 5, to: 1, weight: 0.8),
            DegreeTransition(from: 6, to: 3, weight: 1.0),
            DegreeTransition(from: 6, to: 4, weight: 0.8),
            DegreeTransition(from: 7, to: 1, weight: 1.0),
            DegreeTransition(from: 7, to: 3, weight: 0.8),
        ],
        flavors: [.triad: 1.0, .dominantSeventh: 0.35, .seventh: 1.0, .ninth: 0.4, .eleventh: 0.3, .sus2: 0.5, .sus4: 0.5],
        alterations: [.sharpEleventh],
        devices: [],
        cadenceStrength: 0.3,
        voicing: VoicingOptions(style: .spread)
    )

    /// Electronic.
    static let electronic = StyleProfile(
        id: "electronic",
        name: "Electronic",
        transitions: [
            DegreeTransition(from: 1, to: 4, weight: 1.0),
            DegreeTransition(from: 1, to: 6, weight: 0.8),
            DegreeTransition(from: 1, to: 5, weight: 0.65),
            DegreeTransition(from: 2, to: 5, weight: 1.0),
            DegreeTransition(from: 2, to: 4, weight: 0.8),
            DegreeTransition(from: 3, to: 4, weight: 1.0),
            DegreeTransition(from: 3, to: 6, weight: 0.8),
            DegreeTransition(from: 4, to: 1, weight: 1.0),
            DegreeTransition(from: 4, to: 6, weight: 0.8),
            DegreeTransition(from: 4, to: 5, weight: 0.65),
            DegreeTransition(from: 5, to: 1, weight: 1.0),
            DegreeTransition(from: 5, to: 4, weight: 0.8),
            DegreeTransition(from: 6, to: 4, weight: 1.0),
            DegreeTransition(from: 6, to: 5, weight: 0.8),
            DegreeTransition(from: 7, to: 1, weight: 1.0),
        ],
        flavors: [.triad: 1.0, .dominantSeventh: 0.35, .seventh: 1.0, .ninth: 0.4, .eleventh: 0.3, .sus4: 0.5, .add9: 0.5],
        alterations: [.sharpEleventh],
        devices: [],
        cadenceStrength: 0.6,
        voicing: VoicingOptions()
    )

    /// Cinematic.
    static let cinematic = StyleProfile(
        id: "cinematic",
        name: "Cinematic",
        transitions: [
            DegreeTransition(from: 1, to: 3, weight: 1.0),
            DegreeTransition(from: 1, to: 4, weight: 0.8),
            DegreeTransition(from: 1, to: 6, weight: 0.65),
            DegreeTransition(from: 2, to: 5, weight: 1.0),
            DegreeTransition(from: 2, to: 4, weight: 0.8),
            DegreeTransition(from: 3, to: 4, weight: 1.0),
            DegreeTransition(from: 3, to: 6, weight: 0.8),
            DegreeTransition(from: 4, to: 5, weight: 1.0),
            DegreeTransition(from: 4, to: 1, weight: 0.8),
            DegreeTransition(from: 4, to: 6, weight: 0.65),
            DegreeTransition(from: 5, to: 1, weight: 1.0),
            DegreeTransition(from: 5, to: 6, weight: 0.8),
            DegreeTransition(from: 5, to: 3, weight: 0.65),
            DegreeTransition(from: 6, to: 3, weight: 1.0),
            DegreeTransition(from: 6, to: 4, weight: 0.8),
            DegreeTransition(from: 7, to: 1, weight: 1.0),
            DegreeTransition(from: 7, to: 3, weight: 0.8),
        ],
        flavors: [.triad: 1.0, .dominantSeventh: 0.35, .seventh: 1.0, .ninth: 0.4, .eleventh: 0.3, .thirteenth: 0.3, .sus4: 0.5],
        alterations: [.flatNinth, .sharpNinth, .sharpEleventh, .flatThirteenth],
        devices: [
            DeviceWeight(.neapolitan, weight: 0.5),
            DeviceWeight(.commonToneDiminished, weight: 0.4),
            DeviceWeight(.augmentedSixth(.german), weight: 0.5),
            DeviceWeight(.appliedDominant(target: 5), weight: 0.6),
            DeviceWeight(.borrowed(degree: 1, from: .minor), weight: 0.5),
            DeviceWeight(.borrowed(degree: 4, from: .minor), weight: 0.5),
            DeviceWeight(.borrowed(degree: 6, from: .minor), weight: 0.5),
            DeviceWeight(.borrowed(degree: 7, from: .minor), weight: 0.5),
        ],
        cadenceStrength: 0.6,
        voicing: VoicingOptions(style: .spread)
    )

    /// Bossa.
    static let bossa = StyleProfile(
        id: "bossa",
        name: "Bossa",
        transitions: [
            DegreeTransition(from: 1, to: 3, weight: 1.0),
            DegreeTransition(from: 1, to: 6, weight: 0.8),
            DegreeTransition(from: 1, to: 2, weight: 0.65),
            DegreeTransition(from: 2, to: 5, weight: 1.0),
            DegreeTransition(from: 2, to: 4, weight: 0.8),
            DegreeTransition(from: 3, to: 6, weight: 1.0),
            DegreeTransition(from: 3, to: 2, weight: 0.8),
            DegreeTransition(from: 3, to: 5, weight: 0.65),
            DegreeTransition(from: 4, to: 5, weight: 1.0),
            DegreeTransition(from: 4, to: 2, weight: 0.8),
            DegreeTransition(from: 4, to: 1, weight: 0.65),
            DegreeTransition(from: 5, to: 1, weight: 1.0),
            DegreeTransition(from: 5, to: 6, weight: 0.8),
            DegreeTransition(from: 5, to: 3, weight: 0.65),
            DegreeTransition(from: 6, to: 2, weight: 1.0),
            DegreeTransition(from: 6, to: 5, weight: 0.8),
            DegreeTransition(from: 6, to: 3, weight: 0.65),
            DegreeTransition(from: 7, to: 1, weight: 1.0),
            DegreeTransition(from: 7, to: 3, weight: 0.8),
        ],
        flavors: [.triad: 0.3, .dominantSeventh: 1.0, .seventh: 1.0, .ninth: 0.4, .eleventh: 0.3, .thirteenth: 0.3],
        alterations: [.flatNinth, .sharpEleventh],
        devices: [
            DeviceWeight(.appliedDominant(target: 2), weight: 0.6),
            DeviceWeight(.appliedDominant(target: 5), weight: 0.6),
            DeviceWeight(.relatedSupertonic(target: 2), weight: 0.4),
            DeviceWeight(.relatedSupertonic(target: 5), weight: 0.4),
        ],
        cadenceStrength: 1.0,
        voicing: VoicingOptions(style: .drop2, bassMode: .root)
    )

    /// Samba.
    static let samba = StyleProfile(
        id: "samba",
        name: "Samba",
        transitions: [
            DegreeTransition(from: 1, to: 2, weight: 1.0),
            DegreeTransition(from: 1, to: 5, weight: 0.8),
            DegreeTransition(from: 1, to: 6, weight: 0.65),
            DegreeTransition(from: 2, to: 5, weight: 1.0),
            DegreeTransition(from: 2, to: 4, weight: 0.8),
            DegreeTransition(from: 3, to: 6, weight: 1.0),
            DegreeTransition(from: 3, to: 2, weight: 0.8),
            DegreeTransition(from: 4, to: 5, weight: 1.0),
            DegreeTransition(from: 4, to: 2, weight: 0.8),
            DegreeTransition(from: 4, to: 1, weight: 0.65),
            DegreeTransition(from: 5, to: 1, weight: 1.0),
            DegreeTransition(from: 5, to: 4, weight: 0.8),
            DegreeTransition(from: 6, to: 2, weight: 1.0),
            DegreeTransition(from: 6, to: 5, weight: 0.8),
            DegreeTransition(from: 7, to: 1, weight: 1.0),
            DegreeTransition(from: 7, to: 6, weight: 0.8),
        ],
        flavors: [.triad: 0.3, .dominantSeventh: 1.0, .seventh: 1.0, .ninth: 0.4, .eleventh: 0.3, .thirteenth: 0.3, .add9: 0.5, .sixNine: 0.5],
        alterations: [.flatNinth, .sharpEleventh, .flatThirteenth],
        devices: [
            DeviceWeight(.appliedDominant(target: 5), weight: 0.6),
            DeviceWeight(.tritoneSubstitute(target: 1), weight: 0.6),
            DeviceWeight(.relatedSupertonic(target: 5), weight: 0.4),
        ],
        cadenceStrength: 1.0,
        voicing: VoicingOptions(style: .drop2, bassMode: .root)
    )

    /// African.
    static let african = StyleProfile(
        id: "african",
        name: "African",
        transitions: [
            DegreeTransition(from: 1, to: 4, weight: 1.0),
            DegreeTransition(from: 1, to: 3, weight: 0.8),
            DegreeTransition(from: 1, to: 6, weight: 0.65),
            DegreeTransition(from: 2, to: 4, weight: 1.0),
            DegreeTransition(from: 2, to: 3, weight: 0.8),
            DegreeTransition(from: 3, to: 4, weight: 1.0),
            DegreeTransition(from: 3, to: 1, weight: 0.8),
            DegreeTransition(from: 4, to: 1, weight: 1.0),
            DegreeTransition(from: 4, to: 3, weight: 0.8),
            DegreeTransition(from: 5, to: 1, weight: 1.0),
            DegreeTransition(from: 5, to: 6, weight: 0.8),
            DegreeTransition(from: 6, to: 3, weight: 1.0),
            DegreeTransition(from: 6, to: 1, weight: 0.8),
            DegreeTransition(from: 7, to: 1, weight: 1.0),
        ],
        flavors: [.triad: 1.0, .dominantSeventh: 0.35, .seventh: 0.2, .ninth: 0.4, .eleventh: 0.3, .sus2: 0.5, .sus4: 0.5, .six: 0.5],
        alterations: [],
        devices: [],
        cadenceStrength: 0.6,
        voicing: VoicingOptions()
    )

    /// Indian.
    static let indian = StyleProfile(
        id: "indian",
        name: "Indian",
        transitions: [
            DegreeTransition(from: 1, to: 4, weight: 1.0),
            DegreeTransition(from: 2, to: 4, weight: 1.0),
            DegreeTransition(from: 3, to: 4, weight: 1.0),
            DegreeTransition(from: 3, to: 5, weight: 0.8),
            DegreeTransition(from: 4, to: 5, weight: 1.0),
            DegreeTransition(from: 4, to: 1, weight: 0.8),
            DegreeTransition(from: 5, to: 1, weight: 1.0),
            DegreeTransition(from: 6, to: 5, weight: 1.0),
            DegreeTransition(from: 7, to: 1, weight: 1.0),
        ],
        flavors: [.triad: 1.0, .dominantSeventh: 0.35, .seventh: 0.2, .ninth: 0.4, .eleventh: 0.3, .sus2: 0.5, .sus4: 0.5],
        alterations: [],
        devices: [],
        cadenceStrength: 0.6,
        voicing: VoicingOptions()
    )

    /// Middle Eastern.
    static let middleEastern = StyleProfile(
        id: "middleEastern",
        name: "Middle Eastern",
        transitions: [
            DegreeTransition(from: 1, to: 4, weight: 1.0),
            DegreeTransition(from: 2, to: 4, weight: 1.0),
            DegreeTransition(from: 3, to: 4, weight: 1.0),
            DegreeTransition(from: 4, to: 5, weight: 1.0),
            DegreeTransition(from: 5, to: 1, weight: 1.0),
            DegreeTransition(from: 6, to: 5, weight: 1.0),
            DegreeTransition(from: 7, to: 1, weight: 1.0),
        ],
        flavors: [.triad: 1.0, .dominantSeventh: 0.35, .seventh: 0.2, .ninth: 0.4, .eleventh: 0.3, .sus2: 0.5],
        alterations: [],
        devices: [],
        cadenceStrength: 0.6,
        voicing: VoicingOptions()
    )

    /// Mediterranean.
    static let mediterranean = StyleProfile(
        id: "mediterranean",
        name: "Mediterranean",
        transitions: [
            DegreeTransition(from: 1, to: 2, weight: 1.0),
            DegreeTransition(from: 1, to: 3, weight: 0.8),
            DegreeTransition(from: 1, to: 4, weight: 0.65),
            DegreeTransition(from: 2, to: 5, weight: 1.0),
            DegreeTransition(from: 2, to: 3, weight: 0.8),
            DegreeTransition(from: 3, to: 4, weight: 1.0),
            DegreeTransition(from: 3, to: 6, weight: 0.8),
            DegreeTransition(from: 4, to: 5, weight: 1.0),
            DegreeTransition(from: 4, to: 1, weight: 0.8),
            DegreeTransition(from: 5, to: 1, weight: 1.0),
            DegreeTransition(from: 5, to: 6, weight: 0.8),
            DegreeTransition(from: 6, to: 5, weight: 1.0),
            DegreeTransition(from: 6, to: 1, weight: 0.8),
            DegreeTransition(from: 7, to: 1, weight: 1.0),
        ],
        flavors: [.triad: 1.0, .dominantSeventh: 0.35, .seventh: 0.2, .ninth: 0.4, .eleventh: 0.3, .sus2: 0.5, .sus4: 0.5],
        alterations: [],
        devices: [
            DeviceWeight(.neapolitan, weight: 0.5),
        ],
        cadenceStrength: 1.0,
        voicing: VoicingOptions()
    )

    /// Latin Jazz.
    static let latinJazz = StyleProfile(
        id: "latinJazz",
        name: "Latin Jazz",
        transitions: [
            DegreeTransition(from: 1, to: 2, weight: 1.0),
            DegreeTransition(from: 1, to: 4, weight: 0.8),
            DegreeTransition(from: 1, to: 5, weight: 0.65),
            DegreeTransition(from: 2, to: 5, weight: 1.0),
            DegreeTransition(from: 2, to: 4, weight: 0.8),
            DegreeTransition(from: 3, to: 6, weight: 1.0),
            DegreeTransition(from: 3, to: 2, weight: 0.8),
            DegreeTransition(from: 4, to: 5, weight: 1.0),
            DegreeTransition(from: 4, to: 2, weight: 0.8),
            DegreeTransition(from: 4, to: 1, weight: 0.65),
            DegreeTransition(from: 5, to: 1, weight: 1.0),
            DegreeTransition(from: 5, to: 6, weight: 0.8),
            DegreeTransition(from: 6, to: 2, weight: 1.0),
            DegreeTransition(from: 6, to: 5, weight: 0.8),
            DegreeTransition(from: 7, to: 1, weight: 1.0),
            DegreeTransition(from: 7, to: 5, weight: 0.8),
        ],
        flavors: [.triad: 0.3, .dominantSeventh: 1.0, .seventh: 1.0, .ninth: 0.4, .eleventh: 0.3, .thirteenth: 0.3],
        alterations: [.flatNinth, .sharpNinth, .sharpEleventh, .flatThirteenth],
        devices: [
            DeviceWeight(.tritoneSubstitute(target: 1), weight: 0.6),
            DeviceWeight(.appliedDominant(target: 5), weight: 0.6),
            DeviceWeight(.relatedSupertonic(target: 5), weight: 0.4),
        ],
        cadenceStrength: 1.0,
        voicing: VoicingOptions(style: .drop2, bassMode: .root)
    )

    /// Tango.
    static let tango = StyleProfile(
        id: "tango",
        name: "Tango",
        transitions: [
            DegreeTransition(from: 1, to: 4, weight: 1.0),
            DegreeTransition(from: 1, to: 5, weight: 0.8),
            DegreeTransition(from: 1, to: 6, weight: 0.65),
            DegreeTransition(from: 2, to: 5, weight: 1.0),
            DegreeTransition(from: 2, to: 4, weight: 0.8),
            DegreeTransition(from: 3, to: 4, weight: 1.0),
            DegreeTransition(from: 3, to: 6, weight: 0.8),
            DegreeTransition(from: 4, to: 5, weight: 1.0),
            DegreeTransition(from: 4, to: 2, weight: 0.8),
            DegreeTransition(from: 5, to: 1, weight: 1.0),
            DegreeTransition(from: 5, to: 6, weight: 0.8),
            DegreeTransition(from: 6, to: 2, weight: 1.0),
            DegreeTransition(from: 6, to: 5, weight: 0.8),
            DegreeTransition(from: 7, to: 1, weight: 1.0),
        ],
        flavors: [.triad: 1.0, .dominantSeventh: 1.0, .seventh: 1.0, .ninth: 0.4, .eleventh: 0.3],
        alterations: [.flatNinth, .flatThirteenth],
        devices: [
            DeviceWeight(.appliedDominant(target: 5), weight: 0.6),
            DeviceWeight(.neapolitan, weight: 0.5),
        ],
        cadenceStrength: 1.0,
        voicing: VoicingOptions()
    )

    /// Flamenco.
    static let flamenco = StyleProfile(
        id: "flamenco",
        name: "Flamenco",
        transitions: [
            DegreeTransition(from: 1, to: 5, weight: 1.0),
            DegreeTransition(from: 2, to: 5, weight: 1.0),
            DegreeTransition(from: 3, to: 4, weight: 1.0),
            DegreeTransition(from: 4, to: 5, weight: 1.0),
            DegreeTransition(from: 5, to: 1, weight: 1.0),
            DegreeTransition(from: 6, to: 5, weight: 1.0),
            DegreeTransition(from: 7, to: 1, weight: 1.0),
        ],
        flavors: [.triad: 1.0, .dominantSeventh: 0.35, .seventh: 0.2, .ninth: 0.4],
        alterations: [],
        devices: [
            DeviceWeight(.neapolitan, weight: 0.5),
        ],
        cadenceStrength: 1.0,
        voicing: VoicingOptions()
    )

    /// Celtic.
    static let celtic = StyleProfile(
        id: "celtic",
        name: "Celtic",
        transitions: [
            DegreeTransition(from: 1, to: 4, weight: 1.0),
            DegreeTransition(from: 1, to: 6, weight: 0.8),
            DegreeTransition(from: 1, to: 5, weight: 0.65),
            DegreeTransition(from: 2, to: 5, weight: 1.0),
            DegreeTransition(from: 2, to: 4, weight: 0.8),
            DegreeTransition(from: 3, to: 4, weight: 1.0),
            DegreeTransition(from: 3, to: 6, weight: 0.8),
            DegreeTransition(from: 4, to: 1, weight: 1.0),
            DegreeTransition(from: 4, to: 5, weight: 0.8),
            DegreeTransition(from: 5, to: 1, weight: 1.0),
            DegreeTransition(from: 5, to: 6, weight: 0.8),
            DegreeTransition(from: 6, to: 4, weight: 1.0),
            DegreeTransition(from: 6, to: 1, weight: 0.8),
            DegreeTransition(from: 7, to: 1, weight: 1.0),
        ],
        flavors: [.triad: 1.0, .dominantSeventh: 0.35, .seventh: 0.2, .sus2: 0.5, .sus4: 0.5, .six: 0.5],
        alterations: [],
        devices: [],
        cadenceStrength: 1.0,
        voicing: VoicingOptions()
    )

    /// Impressionist.
    static let impressionist = StyleProfile(
        id: "impressionist",
        name: "Impressionist",
        transitions: [
            DegreeTransition(from: 1, to: 3, weight: 1.0),
            DegreeTransition(from: 1, to: 4, weight: 0.8),
            DegreeTransition(from: 2, to: 5, weight: 1.0),
            DegreeTransition(from: 2, to: 4, weight: 0.8),
            DegreeTransition(from: 3, to: 4, weight: 1.0),
            DegreeTransition(from: 3, to: 6, weight: 0.8),
            DegreeTransition(from: 4, to: 1, weight: 1.0),
            DegreeTransition(from: 4, to: 3, weight: 0.8),
            DegreeTransition(from: 5, to: 1, weight: 1.0),
            DegreeTransition(from: 5, to: 3, weight: 0.8),
            DegreeTransition(from: 6, to: 4, weight: 1.0),
            DegreeTransition(from: 7, to: 1, weight: 1.0),
            DegreeTransition(from: 7, to: 3, weight: 0.8),
        ],
        flavors: [.triad: 0.3, .dominantSeventh: 0.35, .seventh: 1.0, .ninth: 0.4, .eleventh: 0.3, .thirteenth: 0.3, .sus2: 0.5, .sus4: 0.5, .sevenSus4: 0.5],
        alterations: [.flatNinth, .sharpEleventh, .flatThirteenth],
        devices: [
            DeviceWeight(.commonToneDiminished, weight: 0.4),
            DeviceWeight(.neapolitan, weight: 0.5),
            DeviceWeight(.appliedLeadingTone(target: 2), weight: 0.4),
            DeviceWeight(.appliedLeadingTone(target: 5), weight: 0.4),
            DeviceWeight(.borrowed(degree: 1, from: .minor), weight: 0.5),
            DeviceWeight(.borrowed(degree: 4, from: .minor), weight: 0.5),
            DeviceWeight(.borrowed(degree: 2, from: .phrygian), weight: 0.4),
            DeviceWeight(.borrowed(degree: 3, from: .minor), weight: 0.5),
        ],
        cadenceStrength: 0.3,
        voicing: VoicingOptions(style: .spread)
    )

    /// Minimalist.
    static let minimalist = StyleProfile(
        id: "minimalist",
        name: "Minimalist",
        transitions: [
            DegreeTransition(from: 1, to: 4, weight: 1.0),
            DegreeTransition(from: 1, to: 6, weight: 0.8),
            DegreeTransition(from: 1, to: 3, weight: 0.65),
            DegreeTransition(from: 2, to: 4, weight: 1.0),
            DegreeTransition(from: 3, to: 4, weight: 1.0),
            DegreeTransition(from: 3, to: 1, weight: 0.8),
            DegreeTransition(from: 4, to: 1, weight: 1.0),
            DegreeTransition(from: 4, to: 6, weight: 0.8),
            DegreeTransition(from: 5, to: 1, weight: 1.0),
            DegreeTransition(from: 5, to: 6, weight: 0.8),
            DegreeTransition(from: 6, to: 4, weight: 1.0),
            DegreeTransition(from: 6, to: 1, weight: 0.8),
            DegreeTransition(from: 7, to: 1, weight: 1.0),
        ],
        flavors: [.triad: 1.0, .dominantSeventh: 0.35, .seventh: 0.2, .ninth: 0.4, .eleventh: 0.3, .sus2: 0.5, .sus4: 0.5],
        alterations: [],
        devices: [],
        cadenceStrength: 0.3,
        voicing: VoicingOptions()
    )

    /// Avant Garde.
    static let avantGarde = StyleProfile(
        id: "avantGarde",
        name: "Avant Garde",
        transitions: [
            DegreeTransition(from: 1, to: 1, weight: 0.3),
            DegreeTransition(from: 1, to: 2, weight: 0.6),
            DegreeTransition(from: 1, to: 3, weight: 0.6),
            DegreeTransition(from: 1, to: 4, weight: 0.6),
            DegreeTransition(from: 1, to: 5, weight: 0.6),
            DegreeTransition(from: 1, to: 6, weight: 0.6),
            DegreeTransition(from: 1, to: 7, weight: 0.6),
            DegreeTransition(from: 2, to: 5, weight: 1.0),
            DegreeTransition(from: 3, to: 4, weight: 1.0),
            DegreeTransition(from: 3, to: 7, weight: 0.8),
            DegreeTransition(from: 4, to: 7, weight: 1.0),
            DegreeTransition(from: 5, to: 6, weight: 1.0),
            DegreeTransition(from: 5, to: 1, weight: 0.8),
            DegreeTransition(from: 6, to: 5, weight: 1.0),
            DegreeTransition(from: 7, to: 1, weight: 1.0),
        ],
        flavors: [.triad: 0.3, .dominantSeventh: 0.35, .seventh: 1.0, .ninth: 0.4, .eleventh: 0.3, .thirteenth: 0.3],
        alterations: [.flatNinth, .sharpNinth, .sharpEleventh, .flatThirteenth],
        devices: [
            DeviceWeight(.tritoneSubstitute(target: 1), weight: 0.6),
            DeviceWeight(.commonToneDiminished, weight: 0.4),
        ],
        cadenceStrength: 0.3,
        voicing: VoicingOptions()
    )

    /// All styles, in the Harmonicc order.
    static let all: [StyleProfile] = [
        general,
        baroque,
        classical,
        romantic,
        swing,
        bebop,
        modal,
        fusion,
        jazz,
        pop,
        rock,
        folk,
        blues,
        funk,
        rAndB,
        contemporary,
        ambient,
        electronic,
        cinematic,
        bossa,
        samba,
        african,
        indian,
        middleEastern,
        mediterranean,
        latinJazz,
        tango,
        flamenco,
        celtic,
        impressionist,
        minimalist,
        avantGarde,
    ]

    /// The style with this identifier.
    static func named(_ id: String) -> StyleProfile? {
        all.first { $0.id == id }
    }
}
